spring:
  profiles:
    active: dev
  application:
      name: turbine

turbine:
  aggregator:
    clusterConfig: ORGANIZER-QUERY
  appConfig: organizer-query

server:
  port: 7979

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5