spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy.MM.dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
eventuateLocal.kafka.bootstrapServers: ${DOCKER_HOST_IP}:9092
eventuateLocal.zookeeper.connectionString: ${DOCKER_HOST_IP}:2181
eventuateLocal.cdc.dbUserName: root
eventuateLocal.cdc.dbPassword: rootpassword
mongo:
  port: 27017
  host: ${DOCKER_HOST_IP}
server:
  port: 8081