spring:
  profiles:
    active: dev
  application:
    name: organizer-query
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DOCKER_HOST_IP}/eventuate
    username: mysqluser
    password: mysqlpw
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
eventuateLocal.kafka.bootstrapServers: ${DOCKER_HOST_IP}:9092
eventuateLocal.zookeeper.connectionString: ${DOCKER_HOST_IP}:2181
eventuateLocal.cdc.dbUserName: root
eventuateLocal.cdc.dbPassword: rootpassword

server:
  port: 0

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5

feign:
  client:
    config:
      feignName:
        connectTimeout: 10000
        readTimeout: 10000