spring:
  application:
    name: authentication
server:
  port: 9999

#security:
#  oauth2:
#    client:
#      client-id: oauth
#      client-secret: oauth

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG