logging:
  file: mennyei.log
  path: /var/log
  level: 
    org.neo4j.ogm: DEBUG

spring:
  jackson:
    date-format: yyyy.MM.dd HH:mm:ss
    
---
# Development profile specific settings
spring:
    profiles: development