eventuatelocal:
  kafka:
    bootstrap:
      servers: ${DOCKER_HOST_IP}:9092
  zookeeper:
    connection:
      string: ${DOCKER_HOST_IP}:2181
eventuatelocal.cdc.db-user-name: root
eventuatelocal.cdc.db-password: rootpassword

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DOCKER_HOST_IP}/eventuate
    username: mysqluser
    password: mysqlpw

server:
  port: 0

security:
  oauth2:
    client:
      access-TokenUri: http://localhost:9999/oauth/token
      userAuthorizationUri: http://localhost:9999/oauth/authorize
      client-id: oauth
      client-secret: oauth
    resource:
      jwt:
        key-value: '123'